# This is a basic workflow to help you get started with Actions

name: LFS-Warnings

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checklfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: StilleQuelle308/lfs-warning@v3.1.8
        with:
          filesizelimit: 500kb
          exclusionPatterns: |
            **/*.png
          binaryPatterns: |
            **/*.svg
