# This is a basic workflow to help you get started with Actions

name: LFS-Warnings

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checklfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actionsdesk/lfs-warning@v3.1
        with:
          filesizelimit: 1mb
          exclusionPatterns: |
            **/*.png
